"""resume column

Revision ID: 142b6f7bfc93
Revises: d7ec809fdb4a
Create Date: 2025-02-06 14:38:54.391449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142b6f7bfc93'
down_revision = 'd7ec809fdb4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('resume')

    # ### end Alembic commands ###
